I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['raiders1:2200']
INFO:tensorflow:Worker hosts are: ['raiders1:2201', 'raiders1:2202', 'raiders1:2203', 'raiders1:2204', 'raiders2:2205', 'raiders2:2206', 'raiders2:2207', 'raiders2:2208', 'raiders3:2209', 'raiders3:2210', 'raiders3:2211', 'raiders3:2212', 'raiders8:2213', 'raiders8:2214', 'raiders8:2215', 'raiders8:2216']
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.27  Thu Jun  9 18:53:27 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.27.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {raiders1:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2201, raiders1:2202, raiders1:2203, raiders1:2204, raiders2:2205, raiders2:2206, raiders2:2207, raiders2:2208, raiders3:2209, raiders3:2210, raiders3:2211, raiders3:2212, raiders8:2213, raiders8:2214, raiders8:2215, raiders8:2216}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2201
INFO:tensorflow:Learning rate: 0.005000, momentum: 0.600000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 2
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=16; total_num_replicas=16
INFO:tensorflow:Num nodes per compute groups: 8
INFO:tensorflow:Tokens per step: 8
INFO:tensorflow:2016-07-26 08:08:43.520480 Supervisor
E0726 08:08:58.633204913   50887 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2209': timeout occurred
E0726 08:08:58.633475689   50887 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2210': timeout occurred
E0726 08:08:58.633544110   50887 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2211': timeout occurred
E0726 08:08:58.633593495   50887 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2212': timeout occurred
E0726 08:08:59.597660840   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:08:59.597824052   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:08:59.597892090   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:08:59.597964978   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:02.597726524   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:09:02.597855492   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:02.597948227   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:02.598030732   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:09:05.597681989   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:05.597831362   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:09:08.597573661   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:08.597719133   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:09:11.597505351   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:11.597636974   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:09:14.597501694   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:17.597571220   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:09:20.597534614   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:20.597653079   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:09:29.953435456   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:29.953542541   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:09:32.953431513   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:36.929439061   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:09:46.117520470   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:09:54.761540042   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:09:57.761517309   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:10:00.761495037   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:10:16.201504122   50493 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
run-expr-32node.sh: line 23: 49679 Terminated              CUDA_VISIBLE_DEVICES='' bazel-bin/inception/imagenet_distributed_train --batch_size=16 --data_dir=/lfs/local/0/daniter/16node-data-$2 --job_name='worker' --task_id=$2 --ps_hosts='raiders1:2200' --worker_hosts='raiders1:2201,raiders1:2202,raiders1:2203,raiders1:2204,raiders2:2205,raiders2:2206,raiders2:2207,raiders2:2208,raiders3:2209,raiders3:2210,raiders3:2211,raiders3:2212,raiders8:2213,raiders8:2214,raiders8:2215,raiders8:2216' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
