I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['master:2200']
INFO:tensorflow:Worker hosts are: ['master:2201', 'master:2202', 'master:2203', 'master:2204', 'node001:2205', 'node001:2206', 'node001:2207', 'node001:2208', 'node002:2209', 'node002:2210', 'node002:2211', 'node002:2212', 'node003:2213', 'node003:2214', 'node003:2215', 'node003:2216', 'node004:2217', 'node004:2218', 'node004:2219', 'node004:2220', 'node005:2221', 'node005:2222', 'node005:2223', 'node005:2224', 'node006:2225', 'node006:2226', 'node006:2227', 'node006:2228', 'node007:2229', 'node007:2230', 'node007:2231', 'node007:2232']
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GRID K520
major: 3 minor: 0 memoryClockRate (GHz) 0.797
pciBusID 0000:00:03.0
Total memory: 4.00GiB
Free memory: 3.95GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:784] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GRID K520, pci bus id: 0000:00:03.0)
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {master:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {master:2201, master:2202, master:2203, master:2204, node001:2205, node001:2206, node001:2207, node001:2208, localhost:2209, node002:2210, node002:2211, node002:2212, node003:2213, node003:2214, node003:2215, node003:2216, node004:2217, node004:2218, node004:2219, node004:2220, node005:2221, node005:2222, node005:2223, node005:2224, node006:2225, node006:2226, node006:2227, node006:2228, node007:2229, node007:2230, node007:2231, node007:2232}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2209
INFO:tensorflow:Learning rate: 0.050000, momentum: 0.000000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 1
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=32; total_num_replicas=32
INFO:tensorflow:Num nodes per compute groups: 32
INFO:tensorflow:Tokens per step: 32
INFO:tensorflow:2016-08-10 09:03:04.767178 Supervisor
INFO:tensorflow:got sessions! 2016-08-10 09:03:22.904180 
INFO:tensorflow:Started 3 queues for processing input data.
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 3768 get requests, put_count=2855 evicted_count=1000 eviction_rate=0.350263 and unsatisfied allocation rate=0.534236
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
INFO:tensorflow:Step: 7871, Loss: 9.572389, time: 22.237 sec/batch
INFO:tensorflow:Step: 7871, Loss: 9.269161, time: 21.583 sec/batch
INFO:tensorflow:Step: 7872, Loss: 10.071846, time: 15.645 sec/batch
INFO:tensorflow:Step: 7873, Loss: 9.914169, time: 13.934 sec/batch
INFO:tensorflow:Step: 7874, Loss: 10.012327, time: 12.606 sec/batch
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 0 get requests, put_count=1016 evicted_count=1000 eviction_rate=0.984252 and unsatisfied allocation rate=0
INFO:tensorflow:Step: 7875, Loss: 9.905527, time: 11.811 sec/batch
INFO:tensorflow:Step: 7876, Loss: 10.004851, time: 12.807 sec/batch
INFO:tensorflow:Step: 7877, Loss: 8.958423, time: 12.169 sec/batch
INFO:tensorflow:Step: 7878, Loss: 9.818224, time: 13.490 sec/batch
INFO:tensorflow:Step: 7879, Loss: 10.366813, time: 12.710 sec/batch
INFO:tensorflow:Step: 7880, Loss: 9.982119, time: 12.850 sec/batch
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 3768 get requests, put_count=4058 evicted_count=2000 eviction_rate=0.492854 and unsatisfied allocation rate=0.460456
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 281 to 309
INFO:tensorflow:Step: 7881, Loss: 9.760514, time: 13.951 sec/batch
INFO:tensorflow:Step: 7882, Loss: 9.659883, time: 12.625 sec/batch
INFO:tensorflow:Step: 7883, Loss: 9.611384, time: 13.289 sec/batch
INFO:tensorflow:Step: 7884, Loss: 9.110765, time: 13.392 sec/batch
INFO:tensorflow:Step: 7885, Loss: 9.255551, time: 11.874 sec/batch
INFO:tensorflow:Step: 7886, Loss: 9.628922, time: 12.453 sec/batch
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 0 get requests, put_count=1049 evicted_count=1000 eviction_rate=0.953289 and unsatisfied allocation rate=0
INFO:tensorflow:Step: 7887, Loss: 9.407961, time: 13.072 sec/batch
INFO:tensorflow:Step: 7888, Loss: 8.687182, time: 11.836 sec/batch
INFO:tensorflow:Step: 7889, Loss: 9.327439, time: 14.876 sec/batch
INFO:tensorflow:Step: 7890, Loss: 8.875255, time: 12.624 sec/batch
INFO:tensorflow:Step: 7891, Loss: 8.791475, time: 13.474 sec/batch
INFO:tensorflow:Step: 7892, Loss: 9.687217, time: 13.112 sec/batch
INFO:tensorflow:Step: 7893, Loss: 9.642258, time: 11.562 sec/batch
INFO:tensorflow:Step: 7894, Loss: 9.433381, time: 11.399 sec/batch
INFO:tensorflow:Step: 7895, Loss: 8.729145, time: 14.190 sec/batch
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 3768 get requests, put_count=4017 evicted_count=1000 eviction_rate=0.248942 and unsatisfied allocation rate=0.227176
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 1158 to 1273
INFO:tensorflow:Step: 7896, Loss: 9.843762, time: 14.474 sec/batch
INFO:tensorflow:Step: 7897, Loss: 10.055926, time: 11.811 sec/batch
INFO:tensorflow:Step: 7898, Loss: 9.574382, time: 12.427 sec/batch
INFO:tensorflow:Step: 7899, Loss: 8.287632, time: 14.119 sec/batch
INFO:tensorflow:Step: 7900, Loss: 9.615830, time: 12.519 sec/batch
INFO:tensorflow:Step: 7901, Loss: 9.820812, time: 13.057 sec/batch
INFO:tensorflow:Step: 7902, Loss: 9.138295, time: 13.930 sec/batch
INFO:tensorflow:Step: 7903, Loss: 9.112621, time: 12.903 sec/batch
INFO:tensorflow:Step: 7904, Loss: 9.530396, time: 12.617 sec/batch
INFO:tensorflow:Step: 7905, Loss: 8.582122, time: 12.661 sec/batch
INFO:tensorflow:Step: 7906, Loss: 9.316334, time: 13.177 sec/batch
INFO:tensorflow:Step: 7907, Loss: 9.357702, time: 13.285 sec/batch
INFO:tensorflow:Step: 7908, Loss: 9.015567, time: 14.058 sec/batch
INFO:tensorflow:Step: 7909, Loss: 8.551053, time: 13.480 sec/batch
INFO:tensorflow:Step: 7910, Loss: 9.545403, time: 13.082 sec/batch
INFO:tensorflow:Step: 7911, Loss: 8.936136, time: 11.463 sec/batch
INFO:tensorflow:Step: 7912, Loss: 9.687689, time: 13.218 sec/batch
INFO:tensorflow:Step: 7913, Loss: 8.399478, time: 12.414 sec/batch
INFO:tensorflow:Step: 7914, Loss: 8.677699, time: 12.650 sec/batch
INFO:tensorflow:Step: 7915, Loss: 9.089782, time: 12.703 sec/batch
INFO:tensorflow:Step: 7916, Loss: 9.695095, time: 11.391 sec/batch
INFO:tensorflow:Step: 7917, Loss: 9.348602, time: 12.353 sec/batch
INFO:tensorflow:Step: 7918, Loss: 9.097926, time: 13.149 sec/batch
INFO:tensorflow:Step: 7919, Loss: 9.520382, time: 12.108 sec/batch
INFO:tensorflow:Step: 7920, Loss: 9.664968, time: 12.908 sec/batch
INFO:tensorflow:Step: 7921, Loss: 9.854678, time: 13.035 sec/batch
INFO:tensorflow:Step: 7922, Loss: 8.771433, time: 12.969 sec/batch
INFO:tensorflow:Step: 7923, Loss: 9.514268, time: 12.963 sec/batch
INFO:tensorflow:Step: 7924, Loss: 9.038267, time: 12.919 sec/batch
INFO:tensorflow:Step: 7925, Loss: 9.232777, time: 12.416 sec/batch
INFO:tensorflow:Step: 7926, Loss: 9.119184, time: 14.302 sec/batch
INFO:tensorflow:Step: 7927, Loss: 9.271674, time: 11.986 sec/batch
INFO:tensorflow:Step: 7928, Loss: 9.668332, time: 13.791 sec/batch
INFO:tensorflow:Step: 7929, Loss: 9.507981, time: 12.276 sec/batch
INFO:tensorflow:Step: 7930, Loss: 9.170066, time: 12.866 sec/batch
INFO:tensorflow:Step: 7931, Loss: 9.628021, time: 13.128 sec/batch
INFO:tensorflow:Step: 7932, Loss: 9.236744, time: 12.631 sec/batch
INFO:tensorflow:Step: 7933, Loss: 10.020756, time: 12.634 sec/batch
INFO:tensorflow:Step: 7934, Loss: 10.033421, time: 14.577 sec/batch
INFO:tensorflow:Step: 7935, Loss: 9.318202, time: 11.612 sec/batch
INFO:tensorflow:Step: 7936, Loss: 8.570320, time: 13.940 sec/batch
INFO:tensorflow:Step: 7937, Loss: 9.094844, time: 11.781 sec/batch
INFO:tensorflow:Step: 7938, Loss: 8.689427, time: 12.179 sec/batch
INFO:tensorflow:Step: 7939, Loss: 9.118567, time: 13.416 sec/batch
INFO:tensorflow:Step: 7940, Loss: 9.426994, time: 11.077 sec/batch
INFO:tensorflow:Step: 7941, Loss: 9.159001, time: 12.768 sec/batch
INFO:tensorflow:Step: 7942, Loss: 9.321136, time: 13.716 sec/batch
INFO:tensorflow:Step: 7943, Loss: 9.264807, time: 15.363 sec/batch
INFO:tensorflow:Step: 7944, Loss: 9.514888, time: 13.640 sec/batch
INFO:tensorflow:Step: 7945, Loss: 9.199025, time: 13.656 sec/batch
INFO:tensorflow:Step: 7946, Loss: 8.833655, time: 15.322 sec/batch
INFO:tensorflow:Step: 7947, Loss: 9.108697, time: 13.848 sec/batch
INFO:tensorflow:Step: 7948, Loss: 8.742052, time: 13.915 sec/batch
INFO:tensorflow:Step: 7949, Loss: 9.496631, time: 13.769 sec/batch
INFO:tensorflow:Step: 7950, Loss: 9.954410, time: 13.449 sec/batch
INFO:tensorflow:Step: 7951, Loss: 9.826299, time: 13.447 sec/batch
INFO:tensorflow:Step: 7952, Loss: 9.863063, time: 12.962 sec/batch
INFO:tensorflow:Step: 7953, Loss: 9.542121, time: 14.298 sec/batch
E tensorflow/core/distributed_runtime/master_session.cc:923] Cleanup partition error: Unavailable: 
Traceback (most recent call last):
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/__main__/inception/imagenet_distributed_train.py", line 69, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/__main__/inception/imagenet_distributed_train.py", line 65, in main
    inception_distributed_train.train(server.target, dataset, cluster_spec)
  File "/root/models/inception/bazel-bin/inception/imagenet_distributed_train.runfiles/__main__/inception/inception_distributed_train.py", line 330, in train
    loss_value, step = sess.run([train_op, global_step])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 333, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 573, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 648, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 668, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.UnavailableError
run-expr-aws-32node.sh: line 25: 30232 Terminated              CUDA_VISIBLE_DEVICES=$1 bazel-bin/inception/imagenet_distributed_train --batch_size=32 --data_dir=/imagenet/ilsvrc12_train_tfrecord_32_PARTITION/32P_p$2 --job_name='worker' --task_id=$2 --ps_hosts='master:2200' --worker_hosts='master:2201,master:2202,master:2203,master:2204,node001:2205,node001:2206,node001:2207,node001:2208,node002:2209,node002:2210,node002:2211,node002:2212,node003:2213,node003:2214,node003:2215,node003:2216,node004:2217,node004:2218,node004:2219,node004:2220,node005:2221,node005:2222,node005:2223,node005:2224,node006:2225,node006:2226,node006:2227,node006:2228,node007:2229,node007:2230,node007:2231,node007:2232' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
