I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['raiders1:2200']
INFO:tensorflow:Worker hosts are: ['raiders1:2201', 'raiders1:2202', 'raiders1:2203', 'raiders1:2204', 'raiders2:2205', 'raiders2:2206', 'raiders2:2207', 'raiders2:2208', 'raiders3:2209', 'raiders3:2210', 'raiders3:2211', 'raiders3:2212', 'raiders8:2213', 'raiders8:2214', 'raiders8:2215', 'raiders8:2216']
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.27  Thu Jun  9 18:53:27 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.27.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {raiders1:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2201, raiders1:2202, raiders1:2203, raiders1:2204, raiders2:2205, raiders2:2206, raiders2:2207, raiders2:2208, raiders3:2209, raiders3:2210, raiders3:2211, raiders3:2212, raiders8:2213, raiders8:2214, raiders8:2215, raiders8:2216}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2201
INFO:tensorflow:Learning rate: 0.005000, momentum: 0.900000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 4
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=16; total_num_replicas=16
INFO:tensorflow:Num nodes per compute groups: 4
INFO:tensorflow:Tokens per step: 4
INFO:tensorflow:2016-07-26 10:31:42.390827 Supervisor
INFO:tensorflow:Restored model from /lfs/local/0/daniter/cg-snapshot/model.ckpt-399
INFO:tensorflow:got sessions! 2016-07-26 10:32:39.736907 
INFO:tensorflow:Started 3 queues for processing input data.
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Step: 399, Loss: 5.718231, time: 20.393 sec/batch
INFO:tensorflow:Step: 403, Loss: 5.365585, time: 18.921 sec/batch
INFO:tensorflow:Step: 407, Loss: 5.900685, time: 17.804 sec/batch
INFO:tensorflow:Step: 411, Loss: 5.795514, time: 15.147 sec/batch
INFO:tensorflow:Step: 415, Loss: 7.878149, time: 15.614 sec/batch
INFO:tensorflow:Step: 419, Loss: 11.789927, time: 14.028 sec/batch
INFO:tensorflow:global_step/sec: 0.227279
INFO:tensorflow:Step: 423, Loss: 10.391207, time: 14.327 sec/batch
INFO:tensorflow:Step: 429, Loss: 13.494112, time: 15.511 sec/batch
INFO:tensorflow:Step: 433, Loss: 13.365338, time: 15.315 sec/batch
INFO:tensorflow:Step: 437, Loss: 14.774475, time: 14.120 sec/batch
INFO:tensorflow:Step: 441, Loss: 11.599514, time: 23.618 sec/batch
INFO:tensorflow:Step: 447, Loss: 12.268623, time: 31.254 sec/batch
INFO:tensorflow:global_step/sec: 0.225197
INFO:tensorflow:Step: 452, Loss: 9.985083, time: 41.908 sec/batch
INFO:tensorflow:Step: 456, Loss: 8.567003, time: 36.398 sec/batch
INFO:tensorflow:Step: 460, Loss: 7.284888, time: 25.474 sec/batch
INFO:tensorflow:global_step/sec: 0.116654
INFO:tensorflow:Step: 464, Loss: 7.439930, time: 32.188 sec/batch
INFO:tensorflow:Step: 468, Loss: 6.969350, time: 38.131 sec/batch
INFO:tensorflow:Step: 472, Loss: 6.912816, time: 21.842 sec/batch
INFO:tensorflow:Step: 476, Loss: 9.615836, time: 23.644 sec/batch
INFO:tensorflow:Step: 480, Loss: 9.283441, time: 25.345 sec/batch
INFO:tensorflow:global_step/sec: 0.141677
INFO:tensorflow:Step: 484, Loss: 8.746746, time: 27.779 sec/batch
INFO:tensorflow:Step: 488, Loss: 7.375710, time: 20.245 sec/batch
INFO:tensorflow:Step: 492, Loss: 7.338257, time: 18.225 sec/batch
INFO:tensorflow:Step: 496, Loss: 7.737475, time: 20.969 sec/batch
INFO:tensorflow:Step: 500, Loss: 6.559308, time: 17.857 sec/batch
INFO:tensorflow:Step: 504, Loss: 7.593119, time: 16.914 sec/batch
INFO:tensorflow:global_step/sec: 0.199992
INFO:tensorflow:Step: 508, Loss: 6.824125, time: 21.977 sec/batch
INFO:tensorflow:Step: 512, Loss: 6.973993, time: 17.335 sec/batch
INFO:tensorflow:Step: 516, Loss: 6.774275, time: 18.531 sec/batch
INFO:tensorflow:global_step/sec: 0.125002
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:global_step/sec: 0
run-expr-32node.sh: line 23: 64616 Terminated              CUDA_VISIBLE_DEVICES='' bazel-bin/inception/imagenet_distributed_train --batch_size=16 --data_dir=/lfs/local/0/daniter/16node-data-$2 --job_name='worker' --task_id=$2 --ps_hosts='raiders1:2200' --worker_hosts='raiders1:2201,raiders1:2202,raiders1:2203,raiders1:2204,raiders2:2205,raiders2:2206,raiders2:2207,raiders2:2208,raiders3:2209,raiders3:2210,raiders3:2211,raiders3:2212,raiders8:2213,raiders8:2214,raiders8:2215,raiders8:2216' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
