I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['raiders1:2200']
INFO:tensorflow:Worker hosts are: ['raiders1:2201', 'raiders1:2202', 'raiders1:2203', 'raiders1:2204', 'raiders2:2205', 'raiders2:2206', 'raiders2:2207', 'raiders2:2208', 'raiders3:2209', 'raiders3:2210', 'raiders3:2211', 'raiders3:2212', 'raiders8:2213', 'raiders8:2214', 'raiders8:2215', 'raiders8:2216']
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.27  Thu Jun  9 18:53:27 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.27.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {raiders1:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {raiders1:2201, raiders1:2202, localhost:2203, raiders1:2204, raiders2:2205, raiders2:2206, raiders2:2207, raiders2:2208, raiders3:2209, raiders3:2210, raiders3:2211, raiders3:2212, raiders8:2213, raiders8:2214, raiders8:2215, raiders8:2216}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2203
INFO:tensorflow:Learning rate: 0.001000, momentum: 0.600000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 1
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=16; total_num_replicas=16
INFO:tensorflow:Num nodes per compute groups: 16
INFO:tensorflow:Tokens per step: 16
INFO:tensorflow:2016-07-26 08:14:49.111597 Supervisor
E0726 08:15:03.773576198   54950 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2209': timeout occurred
E0726 08:15:03.773830571   54950 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2210': timeout occurred
E0726 08:15:03.773876618   54950 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2211': timeout occurred
E0726 08:15:03.773905877   54950 tcp_client_posix.c:191]     failed to connect to 'ipv4:172.24.75.45:2212': timeout occurred
E0726 08:15:04.461627256   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:04.461790499   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:15:04.461852036   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:15:04.461902367   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:15:07.461450690   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:15:07.461625853   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:10.461505130   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:15:10.461623078   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:15:13.461519780   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:13.461633965   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:15:16.461522190   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:15:16.461647109   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:15:19.461503318   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:22.461491181   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:15:25.461428041   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:15:25.461558167   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:15:29.729548491   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:35.805486180   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:15:42.049496812   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:15:45.049521379   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:15:45.049640241   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
E0726 08:15:57.073534031   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: 113
E0726 08:16:00.073448165   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: 113
E0726 08:16:10.905464434   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: 113
E0726 08:16:13.905412078   54558 tcp_client_posix.c:178]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: 113
run-expr-32node.sh: line 23: 53742 Terminated              CUDA_VISIBLE_DEVICES='' bazel-bin/inception/imagenet_distributed_train --batch_size=16 --data_dir=/lfs/local/0/daniter/16node-data-$2 --job_name='worker' --task_id=$2 --ps_hosts='raiders1:2200' --worker_hosts='raiders1:2201,raiders1:2202,raiders1:2203,raiders1:2204,raiders2:2205,raiders2:2206,raiders2:2207,raiders2:2208,raiders3:2209,raiders3:2210,raiders3:2211,raiders3:2212,raiders8:2213,raiders8:2214,raiders8:2215,raiders8:2216' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
