I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['raiders1:2200']
INFO:tensorflow:Worker hosts are: ['raiders1:2201', 'raiders1:2202', 'raiders1:2203', 'raiders1:2204', 'raiders2:2205', 'raiders2:2206', 'raiders2:2207', 'raiders2:2208', 'raiders3:2209', 'raiders3:2210', 'raiders3:2211', 'raiders3:2212', 'raiders8:2213', 'raiders8:2214', 'raiders8:2215', 'raiders8:2216']
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.27  Thu Jun  9 18:53:27 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.27.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {raiders1:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2201, raiders1:2202, raiders1:2203, raiders1:2204, raiders2:2205, raiders2:2206, raiders2:2207, raiders2:2208, raiders3:2209, raiders3:2210, raiders3:2211, raiders3:2212, raiders8:2213, raiders8:2214, raiders8:2215, raiders8:2216}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2201
INFO:tensorflow:Learning rate: 0.002500, momentum: 0.900000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 4
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=16; total_num_replicas=16
INFO:tensorflow:Num nodes per compute groups: 4
INFO:tensorflow:Tokens per step: 4
INFO:tensorflow:2016-07-26 08:51:35.919211 Supervisor
E0726 08:51:49.962136228   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:49.962239732   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:49.963187511   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:49.963257829   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:51.961889602   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:51.961993851   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:51.962037238   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:51.962089265   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:55.271430017   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:55.496148248   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:55.538597109   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:55.757447716   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:59.919851359   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:01.106850350   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:01.437531705   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:02.250864521   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:08.551183530   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:09.313580125   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:11.460003093   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:12.059136140   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:20.107802751   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:25.021448878   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:29.300198872   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:30.580392697   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:34.546705768   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:53.057188673   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:55.275850984   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:56.757042394   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:59.689810479   78953 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
run-expr-32node.sh: line 23: 78138 Terminated              CUDA_VISIBLE_DEVICES='' bazel-bin/inception/imagenet_distributed_train --batch_size=16 --data_dir=/lfs/local/0/daniter/16node-data-$2 --job_name='worker' --task_id=$2 --ps_hosts='raiders1:2200' --worker_hosts='raiders1:2201,raiders1:2202,raiders1:2203,raiders1:2204,raiders2:2205,raiders2:2206,raiders2:2207,raiders2:2208,raiders3:2209,raiders3:2210,raiders3:2211,raiders3:2212,raiders8:2213,raiders8:2214,raiders8:2215,raiders8:2216' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
