I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
INFO:tensorflow:PS hosts are: ['raiders1:2200']
INFO:tensorflow:Worker hosts are: ['raiders1:2201', 'raiders1:2202', 'raiders1:2203', 'raiders1:2204', 'raiders2:2205', 'raiders2:2206', 'raiders2:2207', 'raiders2:2208', 'raiders3:2209', 'raiders3:2210', 'raiders3:2211', 'raiders3:2212', 'raiders8:2213', 'raiders8:2214', 'raiders8:2215', 'raiders8:2216']
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:153] retrieving CUDA diagnostic information for host: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: raiders1
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:347] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.27  Thu Jun  9 18:53:27 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.27.0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:81] No GPU devices available on machine.
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {raiders1:2200}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {raiders1:2201, raiders1:2202, localhost:2203, raiders1:2204, raiders2:2205, raiders2:2206, raiders2:2207, raiders2:2208, raiders3:2209, raiders3:2210, raiders3:2211, raiders3:2212, raiders8:2213, raiders8:2214, raiders8:2215, raiders8:2216}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2203
INFO:tensorflow:Learning rate: 0.002500, momentum: 0.900000
INFO:tensorflow:Sync mode!!!!!!
INFO:tensorflow:Compute groups : 4
INFO:tensorflow:SyncReplicas enabled: replicas_to_aggregate=16; total_num_replicas=16
INFO:tensorflow:Num nodes per compute groups: 4
INFO:tensorflow:Tokens per step: 4
INFO:tensorflow:2016-07-26 08:51:34.790481 Supervisor
E0726 08:51:47.316354201   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:47.316570508   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:47.316600996   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:47.317319558   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:49.317014647   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:49.317082848   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:49.317105025   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:49.317141649   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:52.519208824   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:52.519383977   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:52.862883197   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:52.874279454   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:51:56.696564716   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:51:56.962747243   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:51:57.549732874   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:51:58.463135611   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:03.686274110   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:04.193024651   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:04.481677307   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:08.985879628   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:12.887497643   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:15.399002905   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:19.004204655   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:25.424255680   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:29.105147889   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:52:33.191259871   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
E0726 08:52:42.067147235   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2209': socket error: connection refused
E0726 08:52:48.194095188   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2212': socket error: connection refused
E0726 08:52:50.486756323   78951 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2211': socket error: connection refused
E0726 08:53:01.554647200   78140 tcp_client_posix.c:173]     failed to connect to 'ipv4:172.24.75.45:2210': socket error: connection refused
run-expr-32node.sh: line 23: 78135 Terminated              CUDA_VISIBLE_DEVICES='' bazel-bin/inception/imagenet_distributed_train --batch_size=16 --data_dir=/lfs/local/0/daniter/16node-data-$2 --job_name='worker' --task_id=$2 --ps_hosts='raiders1:2200' --worker_hosts='raiders1:2201,raiders1:2202,raiders1:2203,raiders1:2204,raiders2:2205,raiders2:2206,raiders2:2207,raiders2:2208,raiders3:2209,raiders3:2210,raiders3:2211,raiders3:2212,raiders8:2213,raiders8:2214,raiders8:2215,raiders8:2216' --initial_learning_rate=$3 --momentum=$4 --sync=True --compute_groups=$5
